import type { Template } from "./types"

export const templates: Template[] = [
  {
    id: "template-1",
    title: "Dashboard Pro",
    description: "A comprehensive admin dashboard template with dark mode support and multiple chart components.",
    price: 49.99,
    category: "dashboard",
    image: "/placeholder.svg?height=400&width=600&text=Dashboard+Pro",
    rating: 4.8,
    reviews: 124,
    features: [
      "Responsive design",
      "Dark mode support",
      "10+ chart components",
      "Form validation",
      "Authentication pages",
      "Data tables with sorting and filtering",
    ],
  },
  {
    id: "template-2",
    title: "E-commerce Bundle",
    description: "Complete e-commerce solution with product listings, cart, checkout, and admin dashboard.",
    price: 79.99,
    category: "ecommerce",
    image: "/placeholder.svg?height=400&width=600&text=E-commerce+Bundle",
    rating: 4.9,
    reviews: 87,
    features: [
      "Product catalog",
      "Shopping cart",
      "Checkout process",
      "User accounts",
      "Order management",
      "Payment integration",
      "Admin dashboard",
    ],
  },
  {
    id: "template-3",
    title: "Landing Page Kit",
    description: "A collection of conversion-focused landing page templates for various industries.",
    price: 29.99,
    category: "landing",
    image: "/placeholder.svg?height=400&width=600&text=Landing+Page+Kit",
    rating: 4.7,
    reviews: 156,
    features: [
      "10+ page templates",
      "Customizable sections",
      "Mobile-first design",
      "SEO optimized",
      "Fast loading",
      "Easy to customize",
    ],
  },
  {
    id: "template-4",
    title: "Blog Template",
    description: "Modern blog template with category pages, author profiles, and comment system.",
    price: 19.99,
    category: "blog",
    image: "/placeholder.svg?height=400&width=600&text=Blog+Template",
    rating: 4.6,
    reviews: 92,
    features: [
      "Responsive design",
      "Category pages",
      "Author profiles",
      "Comment system",
      "Search functionality",
      "Newsletter signup",
    ],
  },
  {
    id: "template-5",
    title: "Portfolio Template",
    description: "Showcase your work with this elegant portfolio template designed for creatives.",
    price: 39.99,
    category: "portfolio",
    image: "/placeholder.svg?height=400&width=600&text=Portfolio+Template",
    rating: 4.8,
    reviews: 68,
    features: [
      "Project showcase",
      "About me section",
      "Contact form",
      "Skills display",
      "Testimonials",
      "Blog integration",
    ],
  },
  {
    id: "template-6",
    title: "SaaS Landing Page",
    description: "Perfect for software-as-a-service companies looking to convert visitors into customers.",
    price: 34.99,
    category: "landing",
    image: "/placeholder.svg?height=400&width=600&text=SaaS+Landing",
    rating: 4.7,
    reviews: 103,
    features: [
      "Feature showcase",
      "Pricing tables",
      "Testimonials",
      "FAQ section",
      "Newsletter signup",
      "Contact form",
    ],
  },
  {
    id: "template-7",
    title: "Real Estate Template",
    description: "Showcase properties and connect with potential buyers with this real estate template.",
    price: 44.99,
    category: "real-estate",
    image: "/placeholder.svg?height=400&width=600&text=Real+Estate",
    rating: 4.5,
    reviews: 76,
    features: [
      "Property listings",
      "Property details page",
      "Agent profiles",
      "Search filters",
      "Map integration",
      "Contact forms",
    ],
  },
  {
    id: "template-8",
    title: "Restaurant Template",
    description: "Showcase your menu and allow online reservations with this restaurant template.",
    price: 24.99,
    category: "restaurant",
    image: "/placeholder.svg?height=400&width=600&text=Restaurant",
    rating: 4.6,
    reviews: 89,
    features: [
      "Menu display",
      "Online reservations",
      "Photo gallery",
      "About section",
      "Contact information",
      "Opening hours",
    ],
  },
  {
    id: "template-9",
    title: "Agency Portfolio",
    description: "Showcase your agency's work and services with this professional template.",
    price: 54.99,
    category: "portfolio",
    image: "/placeholder.svg?height=400&width=600&text=Agency+Portfolio",
    rating: 4.9,
    reviews: 112,
    features: [
      "Project showcase",
      "Team profiles",
      "Service descriptions",
      "Client testimonials",
      "Contact form",
      "Blog section",
    ],
  },
]

